### ISSUE TITLE
After newest libgifski update the generator needs few seconds to start and the progress is laggy

### ISSUE THREAD

**Issue by sunshinejr** [sindresorhus/Gifski#95] opened 2019-06-24 14:39 UTC
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2480%20Funded-%2300A156.svg" />](https://issuehunt.io/r/sindresorhus/gifski-app/issues/95)

# The bounty here now applies to https://github.com/sindresorhus/Gifski/issues/180 instead.

---

This is the video I reproduced it with.

[new_gifski_transitions.mov.zip](https://github.com/sindresorhus/Gifski/files/3321317/new_gifski_transitions.mov.zip)

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $80.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($80.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/gifski-app/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by sindresorhus** [comment] 2019-06-24 14:53
I've made a branch with logging: https://github.com/sindresorhus/Gifski/tree/logging-for-95 I've wrapped the `generateCGImagesAsynchronously` callback in a DispatchQueue, so libgifski won't block it.

Here's the log output:

```
generate 0 2019-06-24 14:51:53 +0000
generate 1 2019-06-24 14:51:53 +0000
generate 2 2019-06-24 14:51:53 +0000
generate 3 2019-06-24 14:51:54 +0000
generate 4 2019-06-24 14:51:54 +0000
generate 5 2019-06-24 14:51:54 +0000
generate 6 2019-06-24 14:51:54 +0000
generate 7 2019-06-24 14:51:54 +0000
generate 8 2019-06-24 14:51:54 +0000
generate 9 2019-06-24 14:51:54 +0000
generate 10 2019-06-24 14:51:54 +0000
generate 11 2019-06-24 14:51:54 +0000
generate 12 2019-06-24 14:51:54 +0000
generate 13 2019-06-24 14:51:54 +0000
generate 14 2019-06-24 14:51:55 +0000
generate 15 2019-06-24 14:51:55 +0000
generate 16 2019-06-24 14:51:55 +0000
generate 17 2019-06-24 14:51:55 +0000
generate 18 2019-06-24 14:51:55 +0000
generate 19 2019-06-24 14:51:55 +0000
generate 20 2019-06-24 14:51:55 +0000
generate 21 2019-06-24 14:51:55 +0000
generate 22 2019-06-24 14:51:55 +0000
generate 23 2019-06-24 14:51:55 +0000
generate 24 2019-06-24 14:51:55 +0000
generate 25 2019-06-24 14:51:55 +0000
generate 26 2019-06-24 14:51:55 +0000
generate 27 2019-06-24 14:51:55 +0000
generate 28 2019-06-24 14:51:55 +0000
generate 29 2019-06-24 14:51:55 +0000
generate 30 2019-06-24 14:51:55 +0000
generate 31 2019-06-24 14:51:55 +0000
generate 32 2019-06-24 14:51:55 +0000
generate 33 2019-06-24 14:51:56 +0000
generate 34 2019-06-24 14:51:56 +0000
write 2019-06-24 14:52:02 +0000
write 2019-06-24 14:52:02 +0000
write 2019-06-24 14:52:02 +0000
write 2019-06-24 14:52:02 +0000
write 2019-06-24 14:52:02 +0000
write 2019-06-24 14:52:02 +0000
write 2019-06-24 14:52:02 +0000
write 2019-06-24 14:52:02 +0000
write 2019-06-24 14:52:02 +0000
write 2019-06-24 14:52:02 +0000
...
```


**Notice how it takes 8 seconds from the last `generate` log to the first `write` log.**

@kornelski Any ideas?

**Comment by sunshinejr** [comment] 2019-06-24 16:50
I also noticed that most of the time when cancelling the process it will crash.

**Comment by kornelski** [comment] 2019-06-24 19:52
What's the order of calls to the library? Are you setting the write callback before the frames?

**Comment by sindresorhus** [comment] 2019-06-24 21:44
Yes: https://github.com/sindresorhus/Gifski/blob/90f809784818af793ed590d8ffaccd19d4fa4c84/Gifski/Gifski.swift#L88

**Comment by sunshinejr** [comment] 2019-07-18 15:28
I spent some time and figured out the culprit. Seems like gifski lib goes to the writing block after we add 3 frames. The problem with this video is that adding these 3 frames takes a long time (2 seconds per each for me). Because of that there is 6 secs+ delay on this video.

I extracted one of the frames and tried to create a gif with that frame using the rust lib and it was a lot quicker. 

Command I used:
```bash
/gifski frame1.png frame1.png frame1.png -o gif.gif
```
Frame I used:
![frame1](https://user-images.githubusercontent.com/5232779/61470371-39f8e900-a981-11e9-9896-c26ef75c2e8b.png)

There might be a difference in how we use the lib, as we pass a data buffer vs I used a PNG image as a frame. Any suggestions @kornelski?

**Comment by BowdusBrown** [comment] 2019-07-22 11:17
## Time profiler 

Release [1.7.0](https://github.com/sindresorhus/Gifski/releases/tag/v1.7.0)

<img width="1009" alt="Screenshot 2019-07-22 at 12 13 55" src="https://user-images.githubusercontent.com/51816980/61628519-72970c00-ac7a-11e9-81f3-898b73dbff86.png">

Release [1.8.0](https://github.com/sindresorhus/Gifski/releases/tag/v1.8.0)

<img width="1010" alt="Screenshot 2019-07-22 at 11 31 58" src="https://user-images.githubusercontent.com/51816980/61628541-7f1b6480-ac7a-11e9-90e9-bed0ad138884.png">

It's clear the function 'addFrame' is taking orders of magnitude longer.

**Comment by BowdusBrown** [comment] 2019-07-22 11:29
Regarding the crashing, it seems to me that the variable `gifData` in the file `Gifski.swift` is potentially touched from several threads and it might need to be locked.

**Comment by sunshinejr** [comment] 2019-07-22 12:07
@BowdusBrown the crash is already fixed in the #94 PR. The only thing right now is the delay in creating frames. I might try to go back to the old gifski version and see if it helps. 

Also, thanks for the findings from the instruments!

**Comment by kornelski** [comment] 2019-07-22 13:20
The compression algorithm hasn't changed between versions, so the raw CPU requirements are identical.

The only thing that has changed is that now the library spawns a thread, instead of expecting the app to spawn one for it.

So I expect delays to come from mutexes/locking/threads waiting on each other.

**Comment by BowdusBrown** [comment] 2019-07-22 15:40
If you take a closer look at my screenshots above, you can see the icon representing code belonging to Gifski (the icon of a human head and shoulders) is shaded out in calls lower down. I believe those calls are inside the libgifski library and I'm curious to know why they appear shaded out in instruments. Anyone know?

**Comment by sunshinejr** [comment] 2019-07-26 16:50
Okay I did a little bit more research. This video behaves similarly between versions, changing between writing/memory doesn't make a difference. It just seems like this video needs a little bit more time to add frames for a gif than normally (I mean it's a lot of pixels).

@sindresorhus I think we can close this one.

**Comment by sunshinejr** [comment] 2019-08-08 13:28
So I was again researching the topic as few things didn't make sense to me. And it turns out that the problem was the optimization level. Basically when we compiled Gifski in Release scheme, everything was back to normal. It only behaved that way on Debug.

**Comment by sindresorhus** [comment] 2019-08-14 11:02
There's still the problem that `gifski.setWriteCallback` (or rather `gifski_set_write_callback` underneath) blocks the thread even though it's documented as being non-blocking. In https://github.com/sindresorhus/Gifski/commit/28be9dceb1878ec175ee0bb0acb92357bab912d3, I had to wrap the `generator.generateCGImagesAsynchronously` callback in `DispatchQueue.global().async`.

**Comment by kornelski** [comment] 2019-08-14 18:18
I can't reproduce that problem. `gifski_set_write_callback` doesn't wait for anything. It only acquires one lock to save thread handle, but there's nothing else that could hold that lock.

**Comment by kornelski** [comment] 2019-08-14 21:38
In 6f6bf34f4fedf4be7aead46bcf230310e2f1665b I've added another warning in case things were called out of order.

**Comment by BowdusBrown** [comment] 2019-08-15 06:07
> @BowdusBrown the crash is already fixed in the #94 PR. The only thing right now is the delay in creating frames. I might try to go back to the old gifski version and see if it helps.
> 
> Also, thanks for the findings from the instruments!

I wouldn't be so sure...

<img width="1016" alt="Screenshot 2019-08-15 at 07 05 39" src="https://user-images.githubusercontent.com/51816980/63075916-2c586400-bf2b-11e9-8c1d-b26e34d9213d.png">

I'm checked out at 6f6bf34f4fedf4be7aead46bcf230310e2f1665b

**Comment by sunshinejr** [comment] 2019-08-15 08:19
Ah yeah, I didn't update the comment, apologies. But after I wrote that comment, we still could get the crash on debug which is non-ideal... On release it seems to be working okayish.

**Comment by BowdusBrown** [comment] 2019-08-15 09:25
No worries. I have provided a fix https://github.com/sindresorhus/Gifski/pull/124 but really the root cause of why gifData is deallocated early is the real fix. It seems to be happening inside the static library.

**Comment by sindresorhus** [comment] 2020-03-11 16:31
Closing as I don't think this is a problem anymore. The bounty here now applies to https://github.com/sindresorhus/Gifski/issues/180 instead.

**Closed by sindresorhus** 2020-03-11 16:31 UTC
Labels: bug, help wanted
