### ISSUE TITLE
Support M1 Chip Native App

### ISSUE THREAD

**Issue by leejongyoung** [sindresorhus/Gifski#235] opened 2021-03-05 01:16 UTC
It's a useful tool
However, I want to support M1 Native App.
Do you support me to run without Rosetta?

**Comment by sindresorhus** [comment] 2021-03-05 03:12
Duplicate of #235

**Comment by sindresorhus** [comment] 2021-03-05 03:13
Duplicate of #215

**Closed by sindresorhus** 2021-03-05 03:13 UTC
