### ISSUE TITLE
Add option to return after converting

### ISSUE THREAD

**Issue by arggh** [sindresorhus/Gifski#135] opened 2019-09-19 13:18 UTC
Would be nice, if one could go back to the trim & settings view after the conversion completes. Even better, if one could preview the end result _before_ actually clicking `Convert` and saving the gif.

**Use case**:

After converting the video to gif, user notices that a) filesize is too large b) resolution wasn't quite the correct choice after all c) framerate drop was too obvious.

Now it would be very handy to keep other settings, including trimming which the user spent a lot of time to get just right, and change only the one setting that required tweaking.

-----

Somewhat related: https://github.com/sindresorhus/Gifski/issues/97

**Comment by sindresorhus** [comment] 2019-09-19 16:25
Duplicate of #112

**Closed by sindresorhus** 2019-09-19 16:25 UTC

**Comment by sindresorhus** [comment] 2019-09-19 16:27
> if one could preview the end result before actually clicking Convert and saving the gif.

You mean preview the GIF? There's no way to show the GIF without actually first converting it. You don't have to save the GIF to preview it though. Just press <kbd>Space</kbd> after the conversion is done to quick look the GIF.

> After converting the video to gif, user notices that a) filesize is too large

We're working on improving the file size estimate, so that should hopefully be less of a problem going forward:  https://github.com/sindresorhus/Gifski/pull/129

**Comment by arggh** [comment] 2019-09-19 17:04
> You mean preview the GIF?

Yes, that was the idea. I think previewing the gif in the same screen where I tweak the conversion settings is a superior user experience compared to going back and forth between the settings-view and the save-view. Especially, since there is already a video player present in the settings-view.

For example, there could be a button <kbd>Render preview</kbd> or a toggle: <kbd>Original</kbd> - <kbd>Preview</kbd>

If you select <kbd>Preview</kbd>, the original video would be replaced with the gif and a progress indicator, that would let me know whenever gifski is busy converting a new preview. Tweaking the settings would start the preview conversion from scratch.

This would make it effortless to tweak the quality and framerate settings.

Another idea to speed up the preview process: how about rendering just the first frame of the gif with the settings applied? That should be plenty fast, and you would get some perspective into what the final result will look like, given the resolution and quality. Maybe even let the user scrub-select frames and render them as needed?

Just an idea.

**Comment by sindresorhus** [comment] 2019-09-19 17:25
@arggh I like your idea. I think we should explore it further. Could you copy-paste your above comment into a new issue focused on the GIF preview idea?
