### ISSUE TITLE
60 FPS

### ISSUE THREAD

**Issue by mehtavatsal** [sindresorhus/Gifski#163] opened 2019-11-16 10:27 UTC
Hi Sindre Sorhus,
Hope you are doing well. I am a big fan of Gifski and using it from past many months. Love the ease of use of the app and output is really good colour accurate. Just love it but I am a UI designer and animator and ask any animator we just love 60 FPS buttery smooth animations. I share my work on dribbble and free dribbble user can upload only GIF. Due to 30 FPS limitation, I can't able to show my actual work on dribbble and you can feel the frustration when you can't able to share your actual work with the world.

Request you please please please add an option of 60 FPS. There are very few apps available but all of them are crap. Big crap. If you will add this feature then it would be awesome. You might be getting few requests for 60 FPS but please add this option.

Keep it up the great work!

Much Love,
Vatsal Mehta

---
Gifski 2.2.1 (24) - com.sindresorhus.Gifski
macOS 10.15.1
MacBookPro14,1

**Comment by sindresorhus** [comment] 2019-11-16 10:45
Duplicate of https://github.com/sindresorhus/Gifski/issues/161

**Comment by sindresorhus** [comment] 2019-11-16 10:45
Can you copy paste the issue text into https://github.com/sindresorhus/Gifski/issues/161 instead?

**Closed by sindresorhus** 2019-11-16 10:45 UTC
