### ISSUE TITLE
Show an alert when given filename already exists

### ISSUE THREAD

**Issue by sunshinejr** [sindresorhus/Gifski#91] opened 2019-06-22 12:58 UTC
When you want to save a GIF with given name and it exists, the Convert button doesn't work - there is no clear message as of **why**.

@sindresorhus did you see this one before?

**Comment by sindresorhus** [comment] 2019-06-22 13:35
Weird. Can you share a screenshot?

This is how it looks (and has always worked) for me:

<img width="450" alt="Screen Shot 2019-06-22 at 20 34 44" src="https://user-images.githubusercontent.com/170270/59964618-32ceee80-952d-11e9-987a-f9cd5a41c5a0.png">

**Comment by sunshinejr** [comment] 2019-06-22 14:08
It just does nothing (highlights normally though).
<img width="726" alt="Zrzut ekranu 2019-06-22 o 16 07 40" src="https://user-images.githubusercontent.com/5232779/59964932-de654800-9507-11e9-9115-0179a4767b9f.png"> 
I wonder if it's the macOS version problem. I'm currently using macOS Catalina.

**Comment by sindresorhus** [comment] 2019-06-22 14:29
> I wonder if it's the macOS version problem. I'm currently using macOS Catalina (beta 1).

Definitely. Since we're just using the stock save panel here. First try upgrading to beta 2, if it's still a problem, report it through the Feedback Assistant app. It's important to get in reports like these now before it's too late to fix.

**Comment by sindresorhus** [comment] 2019-10-24 06:42
Closing as I cannot reproduce in macOS 10.15 final.

**Closed by sindresorhus** 2019-10-24 06:42 UTC
Labels: bug
