### ISSUE TITLE
Crashes when almost complete

### ISSUE THREAD

**Issue by amordicus** [sindresorhus/Gifski#164] opened 2019-11-26 22:08 UTC
So here is the video I'm trying to convert.  The video was taken with a Samsung phone running Android 4.4,; I have no idea if it matters? 
Action taken was reduce to 25%, lowered the quality, FPS was 15.  The conversion stopped at 96% displayed.

My first video that failed was to large to email , so, I have made a shorter video that also failed with the same error message, for your reference the filename is Gifski.mp4: [Gifski.mp4.zip](https://github.com/sindresorhus/Gifski/files/3909493/Gifski.mp4.zip)

---
Gifski 2.3.0 (26) - com.sindresorhus.Gifski
macOS 10.13.6
iMac10,1

**Comment by sindresorhus** [comment] 2019-12-02 04:49
Duplicate of #119

**Comment by sindresorhus** [comment] 2019-12-02 04:49
Thank you so much for sharing a video that reproduces the issue. I have been able to track down the issue and I'll fix it soon.

**Closed** 2019-12-02 16:11 UTC
Labels: bug
